package com.zhouzhou.aries.entity;

// Generated 2016-9-7 23:21:18 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsersLink generated by hbm2java
 */
@Entity
@Table(name = "users_link", catalog = "aries")
public class UsersLink implements java.io.Serializable {

	private Integer id;
	private String userid;
	private String usernanme;
	private String friendid;
	private String friendname;
	private String friendnick;
	private Date createtime;
	private Date update;

	public UsersLink() {
	}

	public UsersLink(String userid, String usernanme, String friendid,
			String friendname, String friendnick, Date createtime, Date update) {
		this.userid = userid;
		this.usernanme = usernanme;
		this.friendid = friendid;
		this.friendname = friendname;
		this.friendnick = friendnick;
		this.createtime = createtime;
		this.update = update;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userid", length = 45)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "usernanme", length = 45)
	public String getUsernanme() {
		return this.usernanme;
	}

	public void setUsernanme(String usernanme) {
		this.usernanme = usernanme;
	}

	@Column(name = "friendid", length = 45)
	public String getFriendid() {
		return this.friendid;
	}

	public void setFriendid(String friendid) {
		this.friendid = friendid;
	}

	@Column(name = "friendname", length = 45)
	public String getFriendname() {
		return this.friendname;
	}

	public void setFriendname(String friendname) {
		this.friendname = friendname;
	}

	@Column(name = "friendnick", length = 45)
	public String getFriendnick() {
		return this.friendnick;
	}

	public void setFriendnick(String friendnick) {
		this.friendnick = friendnick;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update", length = 19)
	public Date getUpdate() {
		return this.update;
	}

	public void setUpdate(Date update) {
		this.update = update;
	}

}
